### ISSUE TITLE
proto-gen: output varies on multiple runs

### ISSUE THREAD

**Issue by nufissime** [Yykz/dofus-unity-rs#1]
Hi,

The output produced by the script seems to vary through multiple runs.

I'm experiencing this on com.ankama.dofus.server.game.protocol.fight.proto, where the structure of FightChallengeJoinRefuseEvent alternates between:

repeated .com.ankama.dofus.server.game.protocol.common.SpellItem slave_spells = 4;
OR
repeated .com.ankama.dofus.server.game.protocol.spell.SpellItem slave_spells = 4;

Any idea of what's happening ?

**Comment by Yykz** [comment]
Yes, this is already noted in the TODO.

The issue arises because all namespaces are stored in a `HashMap`, which is inherently non-deterministic. When trying to retrieve the namespace for two types with the same name, the program prioritizes:

1. Types within the same namespace.
2. Well-known external types.
3. Types with common hierarchical namespaces.

In this case, there is no `SpellItem` in `com.ankama.dofus.server.game.protocol.fight`, nor in the well-known types. When comparing `com.ankama.dofus.server.game.protocol.common` and `com.ankama.dofus.server.game.protocol.spell` with `com.ankama.dofus.server.game.protocol.fight`, both namespaces share the same number of common hierarchical levels, making the result non-deterministic.

In this case, both messages from `com.ankama.dofus.server.game.protocol.fight` and `com.ankama.dofus.server.game.protocol.common` have the exact same definition, so it's not a big deal.

**Comment by nufissime** [comment]
I saw that after creating the issue, but wasn't sure this was the exact reason, thanks for the details.

Could there be some kind of mechanism, in case of duplicates, that would use the first namespace in alphabetical order (or something that could make the code deterministic) ?

I have an automated process that downloads the game, runs your script, and pushes any change to a git repository. Unfortunately, the non-deterministic part generates useless commits.

**Comment by Yykz** [comment]
It should be good, but I don't have the possibility to test right now

**Comment by nufissime** [comment]
I've ran it a dozen times now and the output seems to be deterministic.
Thanks for the quick fix.
